#!/bin/bash

set -e

docker run --rm -i \
-v "$PWD":/go/src/github.com/techdroplabs/rdscheck/ \
-w /go/src/github.com/techdroplabs/rdscheck \
golangci/golangci-lint:v1.16.0 \
golangci-lint run --deadline=5m
