name: ci
on: [push, pull_request]
jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Unit Tests
      run: |
        make unit

    - name: Build
      run: |
        make build check
        make build copy


